name: Deploy to S3

on:
  push:
    branches:
      - main  # Trigger workflow when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Configure AWS Credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Step 3: Install AWS CLI (Optional if not already installed)
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    # Step 4: Sync Files to S3 Bucket
    - name: Deploy to S3
      run: |
        aws s3 sync ./path-to-your-build-folder s3://aitoolhubwebsite --delete
